// import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link'
import navStyles from "./styles/nav.module.css"
import './styles/globals.css'
// import PropTypes from 'prop-types';
import headerStyles from "./page.module.css";
import { CiStar } from "react-icons/ci";
import Home from './page'

export const metadata = {
  title: 'The Book of Many Things',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <nav className={navStyles.navContainer}>
          <div className={navStyles.navContentWrapper}>
            <div className={navStyles.linkContainer}>
              <Link href="/"><button alt="home" className={navStyles.linkButton}>home</button></Link>
              <Link href="/about"><button alt="about" className={navStyles.linkButton}>about</button></Link>
              <Link href="/list"><button alt="list" className={navStyles.linkButton}>list</button></Link>
              <Link href="/add-shelter"><button alt="add a shelter" className={navStyles.linkButton}>add a shelter</button></Link>
              <Link href="/public-api"><button alt="public api" className={navStyles.linkButton}>public api</button></Link>
            </div>
            <CiStar className={navStyles.navIcon}/>
          </div>
        </nav>
        <div className={headerStyles.header}>
          <div className={headerStyles.headerWrapper}>
            <Link href="/">
              <button alt="main page" className={headerStyles.headerLinkButton}>
                <h1 className={headerStyles.title}>The Book Of Many Things</h1>    
              </button>
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}